sudo: required
dist: precise
group: edge

language: java
jdk:
  - oraclejdk7

# whitelist
branches:
  only:
    - dev


install:
  - ant build


cache:
  directories:
    - $HOME/.m2

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_API_KEY
  file: 
    - nightly/faban-kit-dev.tar.gz
  on:
    repo: benchflow/faban
    branch: dev
