sudo: required
dist: precise
group: edge

language: java
jdk:
  - oraclejdk7

# whitelist
branches:
  only:
    - dev


install:
  - ant build


cache:
  directories:
    - $HOME/.m2

deploy:
  provider: releases
  user: $GITHUB_USERNAME
  password: $GITHUB_PASSWORD
  file: 
    - nightly/faban-kit-dev.tar.gz
  skip_cleanup: true
  on:
    repo: benchflow/faban
    branch: dev
