sudo: required
dist: precise
group: edge

language: java
jdk:
  - oraclejdk7

# whitelist
branches:
  only:
    - dev


install:
  - ant build


cache:
  directories:
    - $HOME/.m2

# needed for actually 
before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=devel
  # delete tag if it already exists
  - git tag | grep $GIT_TAG | if [ $(grep -c $GIT_TAG) -eq 1 ]; then git tag -d $GIT_TAG; fi
  - git tag $GIT_TAG -a -m "Development Tag"
  - git push -q https://$GITHUB_OAUTH@github.com/benchflow/faban --tags

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_OAUTH
  file: 
    - nightly/faban-kit-dev.tar.gz
  skip_cleanup: true
  on:
    tags: false
    repo: benchflow/faban
    branch: dev
