sudo: required
dist: precise
group: edge

language: java
jdk:
    - oraclejdk7


install: 
    - ant build
# attempt to skip tests
script: 

cache:
  directories:
    - $HOME/.m2

# whitelist
branches:
  only:
    - dev
    - master